version: "3"

services:
  # dictionary_api:
  #   build: .
  #   ports:
  #     - "8080:8080"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: # your_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: # your_mongo_password
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: # your_mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: # your_mongo_password
      ME_CONFIG_MONGODB_URL:  # your_mongo_url
                              # example: mongodb://myUser:myPassword@mongo:27017/

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
