version: "3"

services:
  expressions_api:
    build: .
    image: expressions_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    network_mode: "host"

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    network_mode: "host"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL:  mongodb://root:example@mongo:27017/
    network_mode: "host"

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    network_mode: "host"
