name: dart_rest_api
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.0
  envify: ^2.0.2
  json_annotation: ^4.4.0
  kiwi: ^4.0.1
  mongo_dart: ^0.7.4
  redis: ^2.2.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  uuid: ^3.0.5
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  envify_generator: ^2.0.2
  http: ^0.13.4
  json_serializable: ^6.1.4
  lints: ^1.0.0
  shelf_router_generator: ^1.0.1
  test: ^1.16.0
